{pkgs}: {
  deps = [
    pkgs.systemd
    pkgs.mesa
    pkgs.libxkbcommon
    pkgs.libdrm
    pkgs.xorg.libxcb
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.at-spi2-atk
    pkgs.pango
    pkgs.cairo
    pkgs.expat
    pkgs.dbus
    pkgs.cups
    pkgs.atk
    pkgs.alsa-lib
    pkgs.nspr
    pkgs.nss
    pkgs.gtk3
    pkgs.glib
    pkgs.xorg.xorgserver
    pkgs.nano
    pkgs.psmisc
    pkgs.gnumake
    pkgs.gcc
    pkgs.python3
  ];
}
