import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/theme-toggle";
import { LanguageSelector } from "@/components/language-selector";
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import afroLogo from "@assets/IMG_5719_1771852498362.png";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="fixed top-0 left-0 right-0 z-50 backdrop-blur-xl bg-background/70 border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-16">
          <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer" data-testid="link-home-logo">
              <img src={afroLogo} alt="Afro AI" className="w-8 h-8 object-contain" />
              <span className="font-bold text-lg">Afro AI</span>
            </div>
          </Link>
          <div className="flex items-center gap-2">
            <LanguageSelector compact />
            <ThemeToggle />
            <Link href="/">
              <Button variant="ghost" size="sm" data-testid="button-back">
                <ArrowLeft className="w-4 h-4 mr-1" />
                Back
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <main className="pt-24 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 prose prose-neutral dark:prose-invert">
          <h1 className="font-serif text-4xl font-bold mb-2" data-testid="text-page-title">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: February 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using Afro AI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.</p>

          <h2>2. Description of Service</h2>
          <p>Afro AI is an AI-powered platform that enables users to create websites and mobile applications. The Platform provides AI code generation, live preview, app publishing to custom subdomains, and project management features.</p>

          <h2>3. User Accounts</h2>
          <p>To use the Platform, you must sign in with a valid Google account. You are responsible for maintaining the security of your account and for all activities that occur under your account.</p>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Platform for any illegal or unauthorized purpose</li>
            <li>Publish content that is harmful, offensive, or violates the rights of others</li>
            <li>Attempt to access, tamper with, or use non-public areas of the Platform</li>
            <li>Use the Platform to distribute malware, spam, or phishing content</li>
            <li>Reverse engineer, decompile, or disassemble any part of the Platform</li>
            <li>Publish apps that impersonate other businesses or individuals</li>
          </ul>

          <h2>5. Content Ownership</h2>
          <p>You retain ownership of the content and code generated through your use of the Platform. However, you grant Afro AI a non-exclusive license to host, display, and distribute your published apps through our subdomain service.</p>

          <h2>6. Published Apps</h2>
          <p>Apps published to subdomains on afroaigroup.com must comply with our acceptable use policy. We reserve the right to remove published apps that violate these terms. Published apps are publicly accessible and you are solely responsible for their content.</p>

          <h2>7. AI-Generated Content</h2>
          <p>Content generated by our AI assistant is provided as-is. While we strive for high quality, we do not guarantee that AI-generated code will be error-free, secure, or suitable for production use without review.</p>

          <h2>8. Subscription Plans</h2>
          <p>The Platform offers free and paid subscription plans. Paid plans provide access to advanced AI models and additional features. Payment processing is handled through Pesapal, supporting Mobile Money, Visa, Mastercard, and bank transfers across Africa. Plan details and pricing are available on our Pricing page.</p>

          <h2>9. Limitation of Liability</h2>
          <p>Afro AI is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Platform, including loss of data, revenue, or business opportunities.</p>

          <h2>10. Termination</h2>
          <p>We reserve the right to suspend or terminate your account at any time for violation of these terms. You may delete your account at any time.</p>

          <h2>11. Changes to Terms</h2>
          <p>We may update these terms from time to time. Continued use of the Platform after changes constitutes acceptance of the updated terms.</p>

          <h2>12. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:Support@afroaigroup.com" className="text-primary">Support@afroaigroup.com</a> or call/WhatsApp us at <a href="https://wa.me/256777815214" className="text-primary">+256 777 815 214</a>.</p>
        </div>
      </main>

      <footer className="border-t py-8 text-center text-sm text-muted-foreground">
        <p>&copy; {new Date().getFullYear()} Afro AI. All rights reserved. Made with love for Africa.</p>
      </footer>
    </div>
  );
}
